learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls',namespace='learning_logs')),
    path('users/', include('users.urls',namespace='users')),
]

learning_logs/urls.py
"""Define padrões de URL para learning_logs."""
from django.urls import path

from . import views

app_name = 'learning_logs'

urlpatterns = [
    #página inicial
    path('', views.index, name='index'),

    #Mostra todos os assuntos
    path('topics/', views.topics, name='topics'),

    #Página de detalhes para um único assunto
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    #página para adicionar um novo assunto
     path('new_topic/', views.new_topic, name='new_topic'),

     #página para adicionar uma nova entrada
     path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

     #página para editar uma entrada
     path('edit_entry/<entry_id>/', views.edit_entry, name='edit_entry')
]

users/urls.py
"""Definir padrão de url para users"""
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'

urlpatterns = [
    #página de login
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    
    #página de logout
    path('logout/', views.logout_view, name='logout'),
    
    #página de cadastro
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic (models.Model):
    """Um assunto sobre o qual o usuário está aprendenddo"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Retorna uma representação em string do modelo."""
        return self.text

class Entry(models.Model):
    """Algo específico aprendido sobre um assunto"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Devolve uma representação em string ddo modelo"""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm



# Create your views here.

def index(request):
    """A página inicial de learnig log"""
    return render(request, 'learning_logs/index.html')

@login_required  #Restringe acesso antes de executar a função
def topics(request):
    """Mostra todos os assuntos"""
    #topics = Topic.objects.order_by('date_added')
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Mostra um asssunto e todas suas entradas"""
    topic = Topic.objects.get(id=topic_id)
    #Garante que o assunto pertence ao usuário atual
    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Adiciona um novo assunto"""
    if request.method != 'POST':
        #Nenhum dado submetido; cria um formulário em branco
        form = TopicForm()
    else:
        #Dados de POST submetidos; processa dados
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            #form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Acrescenta uma nova entrada para um assunto em particular"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        #Nenhum dado submetido; cria um formulário em branco
        form = EntryForm()
    else:
        # Dados de POST submetidos; processa os dados
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
        

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edita uma entrada existente."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #Preenche previamente o formulário com a entrada atual
        form = EntryForm(instance=entry)
    else:
        #POST processa os dados
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
    
    context = {'entry' : entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    """Faz logout do usuário"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """Faz o cadastro de um novo usuário."""
    if request.method != 'POST':
        #Exibe o formulário de cadastro em branco
        form = UserCreationForm()
    else:
        #Processa o formulário preenchido
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            #Faz login e redireciona para a página inicial
            
            authenticate_user = authenticate(username=new_user.username,
                                             password=request.POST['password1'])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    
    context = {'form': form}
    return render(request, 'users/register.html', context)
    

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de Aprendizagem</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
  
  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
            Registro de Aprendizagem</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:topics' %}">Tópicos</a></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Olá , {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
        
      </div>
    </nav>
    
    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Editar Entrada:</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Salvar Alterações<button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
    
{% block header %}
    <div class="jumbotron">
        <h1>Acompanhe seu aprendizado</h1>
    </div>
{% endblock header %}

{% block content %}
<h2>
    {% if user.is_authenticated == False %}
    <a href="{% url 'users:register' %}">Cadastrar uma conta</a>
    {% endif %}
    <br>
    <p>O Registro de Aprendizagem ajuda você a acompanhar
         seu aprendizado, para qualquer tópico que você esteja 
         aprendendo.</p>
</h2>
<h2>
    <p>Sempre que você aprender algo novo sobre um tópico, faça uma anotação
resumindo o que você aprendeu.</p>
</h2>
{% endblock content %}     

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Adicionar nova entrada:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Adicionar Entrada</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Adicione um novo tópico</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Adicionar tópico</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
<h2>Tópico - {{ topic }}</h2>
{% endblock header %}


{% block content %}
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Adicionar nova Entrada</a>
</p>

{% for entry in entries %}  
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">Editar Entradas</a>
                </small>
            </h3>
        </div>
        <div class="panel-body">
            {{ entry.text|linebreaks }}
        </div>
    </div><!-- panel -->
{% empty %}
  Ainda não há entradas para este tópico.     
{% endfor %}
        
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h1>Assuntos</h1>
{% endblock header %}

{% block content %}

<ul>
    {% for topic in topics %}
    <li>
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic.text }} </a>
        </h3>
    </li>
    {% empty %}
    <li>Nenhum tópico foi adicionado ainda.</li>
    {% endfor %}
</ul>

<h3>
    <a href="{% url 'learning_logs:new_topic' %}">Adicionar um novo tópico</a>
</h3>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Entre na sua conta.</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'users:login' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Cadastrar</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>

{% endblock content %}